### ISSUE TITLE
Implement Docker containers

### ISSUE THREAD

**Issue by artdevgame** [namesco/our-boxen-old#3]
Using Docker we can more closely resemble the different live environments and transfer each of their dependencies into their own container.

**Comment by far-blue** [comment]
Just an update on this. There is now an almost consistently working install script for docker-machine, docker and docker-compose that:
* creates a dev vm
* extends it with an additional network interface so it can talk to the dev network
* configures some additional directory shares
* configures a static ip address for the host-only interface so we know what IP address to use in dnsmasq / resolv
* sets up the vm's docker daemon to support the internal docker registry
* pre-installs, configures and runs the memcached container and the web proxy container

Things still to fix:
* There is a bug in boot2docker's docker daemon restart code (docker/machine#1027)
* The way of actually installing the OS X docker client is unclear now boot2docker is being superseded (docker/docker#12501)
* Creation of vm's sometimes fails (various issues raised against docker/machine related to virtual box's networking)
* With the release of 1.6.0 the static ip work can be tidied up

Install scripts are in the private svn Docker repo.

Alongside this, there is a private registry (although this needs upgrading) with images:
* base - ubuntu 14.04 + supervisord
* apache
* php5.5
* compass

logs, other than apache, are available via supervisorctl which you can launch through docker exec

still to do with the images:
* email handling
* ssl support
* a container for roundcube
* a container for libsass for when/if we convert over website
 
Image source files (Docker files etc.) are in the internal svn Docker repo.

Also, a number of our actual projects now have docker-compose.yml files.

All of this also needs some documenting and, of course, actually converting over to using Boxen to run the install script.

**Comment by far-blue** [comment]
I've tracked down one possible cause of the 'sometimes failing to create' which I've raised as an issue (docker/machine#1031) and concerns a possible bug in the way docker-machine calculates the host port for ssh forwarding

**Comment by far-blue** [comment]
I also had a response over the weekend regarding a static OSX client cli (docker/docker#12501). There is already a build available but no-one thought to add it to any docs. I've added this to the install script for now but, like docker-machine and docker-compose, we can break it out into boxen instructions later.

**Comment by far-blue** [comment]
Also, over lunch, I've split the bootlocal.sh script into bootlocal.sh and bootsync.sh scripts (newly supported in 1.6.0) which should be much better as it means no need to restart docker on vm startup. Can't test it yet, though, as I keep hitting docker/machine#1031

**Comment by far-blue** [comment]
I've:
* Ported the install script crudely over to boxen (not yet merged to master or pushed back to origin).
* updated everything to latest versions (docker 1.7, machine 0.3.0, compose 1.3) which has fixed a number of issues.
* updated the install script to play nicely with the changes in machine 0.3.0.
* tweaked the dnsmasq install to work with docker
* Modified the nginx-proxy image to support CORS
* slightly reorganised the image source repo to support tags for different php versions
* separated out the apache stuff from the php stuff so you can easily pick which php version you want to use
* created fpm containers for php5.3, 5.5 and 5.6
* created a special version of the mysql container with no volume mounts specifically designed for throw-away unit testing
* created unittest containers that can run thing db and then the complete test collection or only specific tests
* fixed a couple of issues with timezones and ruby
* updated / added support for docker (both for dev and unit test) to more projects
* pretty much entirely switched to docker for my own dev environment

still to do:
* more docs
* SSL
* roundcube postfix / exim / cirus / dovecot container
